
spring:
  #swagger 3.0 -> spring boot 2.6 -> strategy path_pattern_parser changed
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: 'jdbc:h2:mem:library'
    username: 'user'
    password: ''
    driver-class-name: org.h2.Driver
    schema: classpath:/h2/schema.sql
    data: classpath:/h2/data.sql
    initialization-mode: always # 더미 데이터 생성 설정 always : 서버 재기동 마다 schema, data 새로 생성
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
      path: '/h2-console'

#  sql:
#    init:
#      schema-locations: classpath:/h2/schema.sql
#      data-locations: classpath:/h2/data.sql
