drop table if exists book CASCADE;
drop table if exists member CASCADE;
drop table if exists member_entrust_history CASCADE;
drop table if exists member_rental_history CASCADE;

create table book (
          book_seq bigint generated by default as identity,
          isbn varchar(255),
          name varchar(255),
          type varchar(255),
          primary key (book_seq)
);

create table member (
            member_seq bigint generated by default as identity,
            email varchar(255),
            name varchar(255),
            password varchar(255),
            phone varchar(255),
            primary key (member_seq)
);

create table member_entrust_history (
            member_entrust_seq bigint generated by default as identity,
            book_name varchar(255),
            isbn varchar(255),
            status integer,
            entrust_price integer,
            member_member_seq bigint,
            primary key (member_entrust_seq)
);

create table member_rental_history (
           member_rental_seq bigint generated by default as identity,
           book_name varchar(255),
           isbn varchar(255),
           status integer,
           member_member_seq bigint,
           primary key (member_rental_seq)
);

alter table member_entrust_history
    add constraint FKk0pckcnq3qxuoxmjadiw6husg
        foreign key (member_member_seq)
            references member;

alter table member_rental_history
    add constraint FK1oqemj3smhj61fr69i6whq3vu
        foreign key (member_member_seq)
            references member;



