drop table if exists book CASCADE;
drop table if exists member CASCADE;
drop table if exists member_entrust_history CASCADE;
drop table if exists member_rental_history CASCADE;

create table book (
          book_seq bigint generated by default as identity,
          isbn varchar(255),
          name varchar(255),
          type varchar(255),
          primary key (book_seq)
);

create table member (
            member_seq bigint generated by default as identity,
            email varchar(255),
            name varchar(255),
            password varchar(255),
            phone varchar(255),
            primary key (member_seq)
);

create table book_entrust_history (
            book_entrust_seq bigint generated by default as identity,
            book_name varchar(255),
            isbn varchar(255),
            status varchar(30),
            entrust_price integer,
            member_member_seq bigint,
            rental_count bigint DEFAULT 0,
            registration_date timestamp NULL,
            primary key (book_entrust_seq)
);

create table book_rental_history (
           book_rental_seq bigint generated by default as identity,
           book_name varchar(255),
           isbn varchar(255),
           status varchar(30),
           member_member_seq bigint,
           primary key (book_rental_seq)
);

alter table book_entrust_history
    add constraint FKk0pckcnq3qxuoxmjadiw6husg
        foreign key (member_member_seq)
            references member;

alter table book_rental_history
    add constraint FK1oqemj3smhj61fr69i6whq3vu
        foreign key (member_member_seq)
            references member;



